---
- name: Install curl
  hosts: vms
  remote_user: root

  tasks:
  - name: Ensure curl is at the latest version
    ansible.builtin.apt:
      name: curl
      state: latest
  - name: Ensure nginx is at the latest version
    ansible.builtin.apt:
      name: nginx
      state: latest