---
- name: install packages
  hosts : webservers
  become: yes
  tasks:
    - name: install nginx
      apt:
        name:
          - nginx
          - redis
          - mariadb-server
          - mariadb-client
        state: latest
        update_cache: yes
    - name : start services
      service :
        name : "{{ item }}"
        state : started
        enabled : yes
      with_items:
        - nginx
        - mariadb



