---
- name: install packages
  hosts : webservers
  become: yes
  vars_files:
    - db_vars.yml
  tasks:
    - name: install nginx
      apt:
        name:
          - nginx
          - redis
          - mariadb-server
          - mariadb-client
          - python3-pymysql
        state: latest
        update_cache: yes
    - name : start services
      service :
        name : "{{ item }}"
        state : started
        enabled : yes
      with_items:
        - nginx
        - mariadb
    - name : create mysql server
      mysql_user:
        name: "{{ db_name }}"
        password: "{{ db_password }}"
        state: present
        priv: "{{ db_username }}.*:ALL,GRANT"




